[build.environment]
  TZ = 'America/Chicago'

[[headers]]
  for = "/*xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/data/human.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
